### ISSUE TITLE
Error when call beforeUnload event

### ISSUE THREAD

**Issue by nguyendn** [Rich-Harris/simulant#6]
It has this error when I try to call `beforeUnloadEvent'

```
TypeError: 'undefined' is not an object (evaluating 'maps__initialisersByGroup[group][1]')
```

**Comment by Rich-Harris** [comment]
Thanks! This is fixed in 0.1.4. Be aware though that `BeforeUnloadEvent` can't be used as a constructor (i.e. you can't do `event = new BeforeUnloadEvent(...)`, unlike `new Event(...)`), so simulant has to fall back to a generic `Event` whose type is `beforeunload`. As far as I know there isn't a better way to fake it.
